#!/usr/bin/env python3
# Digit fonts for the Motorola main-screen frequency readout.
#   MOTO_DIG    24 px tall  -- the MHz / kHz digits
#   MOTO_DIG_SM 15 px tall  -- the 100 Hz + 10 Hz digits, drawn smaller so the
#                              fine-tuning digits are visually de-emphasised
# DejaVu Sans Condensed *regular* (not bold) -> thin strokes, open (un-slashed)
# zero.  Rendered large, cropped to the digit band, squashed horizontally so
# "145.55000" fits 128 px.
#
# Output: column-major.  MOTO_DIG    = 3 bytes/column (byte 0 bit 0 = top).
#                        MOTO_DIG_SM = 2 bytes/column.

from PIL import Image, ImageFont, ImageDraw

FONT   = "/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed.ttf"
CHARS  = "0123456789.-"
GAP    = 1

def build(name, pxh, size, squash, npages, chars):
    f = ImageFont.truetype(FONT, size)
    z = f.getbbox("0")                       # digit band, in render-space y
    top, bot = z[1] - 1, z[3] + 1

    def glyph(ch):
        b = f.getbbox(ch)
        cv = Image.new("L", (b[2] + 6, bot + 6), 0)
        ImageDraw.Draw(cv).text((3, 0), ch, fill=255, font=f)
        g = cv.crop((max(0, b[0] - 1), top, b[2] + 1, bot))
        g = g.resize((max(1, round(g.width * squash)), pxh), Image.LANCZOS)
        px = g.load()
        cols = []
        for x in range(g.width):
            t = [0] * npages
            for y in range(pxh):
                if px[x, y] >= 100:
                    t[y >> 3] |= 1 << (y & 7)
            cols += t
        return g.width, cols

    gl = [glyph(c) for c in chars]
    wmax = max(w for w, _ in gl)

    print('// generated by tools/gen_bigdigits.py -- %d px DejaVu Sans Condensed'
          % pxh)
    print('#define %s_MAXW  %d' % (name, wmax))
    print('static const uint8_t %s_W[%d] = { %s };' %
          (name, len(chars), ", ".join(str(w + GAP) for w, _ in gl)))
    print('static const uint8_t %s[%d][%d] = {' % (name, len(chars), wmax * npages))
    for (w, cols), ch in zip(gl, chars):
        cols = list(cols) + [0] * ((wmax - w) * npages)
        print('  { %s },  // %s' % (", ".join("0x%02X" % v for v in cols), repr(ch)))
    print('};\n')

    # preview
    print('/* %s preview' % name)
    for (w, cols), ch in zip(gl, chars):
        print(repr(ch))
        for y in range(pxh):
            print('  ' + ''.join('#' if (cols[x*npages + (y >> 3)] >> (y & 7)) & 1
                                 else '.' for x in range(w)))
    print('*/\n')

build("MOTO_DIG",    24, 42, 0.50, 3, CHARS)
build("MOTO_DIG_SM", 13, 24, 0.44, 2, "0123456789")


# --- 6 px header font: digits + uppercase, for the inverted status bar so it
#     clears both the top and bottom edge of the 8 px bar ---------------------
def build_hdr(size, squash):
    f  = ImageFont.truetype(FONT, size)
    z  = f.getbbox("0")
    top, bot = z[1], z[3]
    chars = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ+-"

    def glyph(ch):
        b  = f.getbbox(ch)
        cv = Image.new("L", (b[2] + 6, bot + 6), 0)
        ImageDraw.Draw(cv).text((3, 0), ch, fill=255, font=f)
        g  = cv.crop((max(0, b[0] - 1), top, b[2] + 1, bot))
        g  = g.resize((max(1, round(g.width * squash)), 6), Image.LANCZOS)
        px = g.load()
        cols = []
        for x in range(g.width):
            v = 0
            for y in range(6):
                if px[x, y] >= 62:
                    v |= 1 << y
            cols.append(v)
        while len(cols) > 1 and cols[0] == 0:  cols = cols[1:]
        while len(cols) > 1 and cols[-1] == 0: cols = cols[:-1]
        return len(cols), cols

    gl   = [glyph(c) for c in chars]
    wmax = max(w for w, _ in gl)
    print('// 6 px header font (digits 0-9 then A-Z), 1 byte/column, bit0 = top')
    print('#define HDR6_MAXW  %d' % wmax)
    print('static const uint8_t HDR6_W[%d] = { %s };' %
          (len(chars), ", ".join(str(w) for w, _ in gl)))
    print('static const uint8_t HDR6[%d][%d] = {' % (len(chars), wmax))
    for (w, cols), ch in zip(gl, chars):
        cols = cols + [0] * (wmax - w)
        print('  { %s },  // %s' % (", ".join("0x%02X" % v for v in cols), ch))
    print('};\n')
    print("/* HDR6 preview")
    for (w, cols), ch in zip(gl, chars):
        print(ch)
        for y in range(6):
            print('  ' + ''.join('#' if (cols[x] >> y) & 1 else '.' for x in range(w)))
    print('*/')

build_hdr(22, 0.50)
